# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/mytestthing',
                'doc_host': 'https://davidrd123.github.io',
                'git_url': 'https://github.com/davidrd123/mytestthing',
                'lib_path': 'mytestthing'},
  'syms': {'mytestthing.core': {'mytestthing.core.foo': ('core.html#foo', 'mytestthing/core.py')}}}
